version: '3.8'
services:
    postgres-db:
        restart: always
        container_name: mlflow_db
        image: postgres:14.0
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DATABASE: ${POSTGRES_DATABASE}
        volumes:
            - mlflow-db:/var/lib/postgresql/data
    waitfordb:
        image: dadarek/wait-for-dependencies
        depends_on:
            - postgres-db
        command: postgres-db:5432

    mlflow-server:
        restart: always
        container_name: mlflow_server
        depends_on:
            - waitfordb
        build: ./mlflow
        ports:
            - 0.0.0.0:5000:5000
        environment:
            DB_URI: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/${POSTGRES_DATABASE}
            MLFLOW_TRACKING_USERNAME: "${MLFLOW_TRACKING_USERNAME}"
            MLFLOW_TRACKING_PASSWORD: "${MLFLOW_TRACKING_PASSWORD}"
            MLFLOW_ARTIFACT_ROOT: "${MLFLOW_ARTIFACT_ROOT}"
        volumes:
                - "${MLFLOW_ARTIFACT_ROOT}:${MLFLOW_ARTIFACT_ROOT}"
        entrypoint: ./start_mlflow_server.sh

volumes:
    mlflow-db:

